### ISSUE TITLE
Add More Arguments to Improve the overview_crossplot Function

### ISSUE THREAD

**Issue by brichard1638** [cosimameyer/overviewR#12]
It is requested that two critical arguments be added to this plot function as summarized below:
- Add a color argument that allows the user to select the color to be added to the plot
- Add a size argument that allows the user to modify the size of the geom points

In the current version of the plot, the geom points are too small and should be user-controlled for size.

**Comment by cosimameyer** [comment]
@brichard1638 thanks also for these suggestions - I appreciate your time to take a look at `overviewR` 🙂

Your suggestions are currently not implemented but it's a great idea (we have them already partly in `overview_plot`; see also #10). 
Until we have them as a permanent implementation in `overview_crossplot` as well, you could use `ggplot2`'s layering logic to solve your problem.

Here are some MWE:

1. Manually add color to the plot

```
overview_crossplot(
    toydata,
    id = ccode,
    time = year,
    cond1 = gdp,
    cond2 = population,
    threshold1 = 25000,
    threshold2 = 27000,
    color = TRUE,
    label = TRUE
)  + scale_color_brewer(palette="Dark2")
```

<img width="850" alt="Screenshot 2022-08-08 at 21 10 24" src="https://user-images.githubusercontent.com/7782895/183495762-aa04ceee-6a69-4c31-a8f6-01257d1a78ce.png">

Or

```
overview_crossplot(
    toydata,
    id = ccode,
    time = year,
    cond1 = gdp,
    cond2 = population,
    threshold1 = 25000,
    threshold2 = 27000,
    color = TRUE,
    label = TRUE
)  +scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#E06910"))
```

<img width="850" alt="Screenshot 2022-08-08 at 21 12 05" src="https://user-images.githubusercontent.com/7782895/183495709-145a0b5b-fb1e-4983-86e4-a4d67eec6bef.png">

2. Change size of geoms. 

```
overview_crossplot(
    toydata,
    id = ccode,
    time = year,
    cond1 = gdp,
    cond2 = population,
    threshold1 = 25000,
    threshold2 = 27000,
    color = TRUE,
    label = TRUE
)  + ggrepel::geom_text_repel(size = 5)
``` 

(this is extremely large now, but it's just to demonstrate the logic 🙂)

<img width="850" alt="Screenshot 2022-08-08 at 21 21 22" src="https://user-images.githubusercontent.com/7782895/183497437-e195add3-8f9c-4ca0-830e-59544e124a26.png">


(I know it's not ideal because it overlaps with the old layers but if you want to have an exploratory look at the data, you'll get at least (for now) some more insights without zooming 🙂)

----

Were these (temporary) solutions you were looking for?

I will add your ideas to our feature requests list for the next release to implement them as permanent solutions, thanks for your ideas! 🙂

**Comment by brichard1638** [comment]
Cosima:::

It was nice hearing from you! Thank you for the prompt response and the code you provided in response to my reported issues.

It is much appreciated.

I am enjoying working with the overviewR package and find it very useful.

Warm regards,

Brice Richard
Data Scientist
Washington, DC USA
________________________________

**Comment by cosimameyer** [comment]
Hi Brice,

That's so great to hear - I'm very happy that you enjoy working with overviewR and thanks for sharing your thoughts on future improvement, it's much appreciated ☺️

Cosima
