### ISSUE TITLE
dont reiterate devtools installs in code sections

### ISSUE THREAD

**Issue by drmowinckels** [cosimameyer/overviewR#21]
As part of (https://github.com/openjournals/joss-reviews/issues/4740)

dont re-iterate the devtools install commands in subsequent readme demo sections. Readme usage sections should assume the tools was installed at the beginning, and not have install bits on top of every code section. It can be confusing for novices to think the tool needs several re-installs.

**Comment by cosimameyer** [comment]
Thanks for the super helpful suggestion. This was a left over from the development process (when the function was just implemented in the development version). I removed it but kept the call of `magrittr` (because it's not essential for `overviewR` but necessary in this specific code chunk). 
The changes are included in PR #25
